FASE3-043 [E2E-TEST] Como cliente quiero pagar la suscripcion de Membresia Premium
gustavosr98/petromiles pull request #16
Opened 2020-08-10 06:11 UTC by GabTovarUCAB

## Checklist para el pull request

**IMPORTANTE**: Revisa que tu PR no este dirigido a Master  
**NOTA**: Agrega al PR las etiquetas de Github que te parezcan esten relacionadas

- [ ] Este PR es un WIP (Work In Progress) para recibir _feedback_ de otros antes de culminar la funcionalidad

Para estar seguro de tu pull request, completa este checklist:

- [x] Estás haciendo el pull request a una rama diferente a la de master.
- [x] Estás haciendo el pull request desde la rama correcta.
- [x] El código compila sin errores.
- [x] Le coloque al título el mismo nombre que el de la tarjeta de Trello.

## Tipo de cambio para PetroMiles

- [x] Nueva historia de usuario completada
- [ ] Funcionalidad relacionada con API externas
- [ ] Corrección de algún problema
- [ ] Alguna mejora añadida

## Cambios propuestos

Automatización de pruebas E2E para Comprar Suscripción a Premium en la plataforma Petromiles
contiene los siguientes casos:
1. El usuario compra la membresía correctamente
2. El usuario trata de comprar nuevamente la membresía mientras sigue en proceso la primera compra.

[Tarjeta de Trello FASE3-043](https://trello.com/c/9YlMYpJ4/195-fase3-043-e2e-test-como-cliente-quiero-pagar-la-suscripcion-de-membresia-premium)

## ¿Cómo probar?

1. Correr el backend y el frontend.
2. Registrar una cuenta en petromiles con las siguientes credenciales: **correo**: `test@petromiles.com` **contraseña**: `test1234`
3. Crea una cuenta bancaria con ese usuario y verifiquela.
4. Para iniciar la interfaz de Cypress, utilizando una ventana de comandos o powershell, ubiquese en la carpeta front-end del proyecto (`/petromiles-frontend`) y ejecute el siguiente comando: **`npm run cypress:open`**, se estara abriendo la siguiente ventana:

![image](https://user-images.githubusercontent.com/55888512/89755691-509f4000-daae-11ea-9f54-f03faca5e622.png)

5. Haga click en el enlace resaltado en verde, de nombre **`subscription-payment.spec.js`**
6. A continuación se ejecutarán las pruebas
7. Espere a que finalicen, y obtendrá los resultados de cypress.

2020-08-10 23:36 UTC, gustavosr98 requested changes
En estas pruebas creo que el _**".ok-btn" realmente no te da la certeza que todo haya salido bien**_. Ese botón también se muestra cuando algo sale mal. Hace falta un **assert** que te asegure que **ocurrió lo esperado**.

![image](https://user-images.githubusercontent.com/40648663/89841236-71b07100-db40-11ea-8daf-498026d563e5.png)

![image](https://user-images.githubusercontent.com/40648663/89841273-87be3180-db40-11ea-8e12-c88fb8401e8a.png)

2020-08-11 08:00 UTC, GabTovarUCAB commented
Agregado asserts para detectar cuáles mensajes aparecen en cada modal incluido la alerta de confirmación. :like:

1. El usuario compra la membresía correctamente:
![image](https://user-images.githubusercontent.com/55888512/89872378-d8587d80-db86-11ea-9de1-5334e60fa984.png)

2. El usuario trata de comprar nuevamente la membresía mientras sigue en proceso la primera compra:
![image](https://user-images.githubusercontent.com/55888512/89872449-f3c38880-db86-11ea-9f64-cdac64dde264.png)

2020-08-11 08:26 UTC, christianneiraUCAB approved these changes

2020-08-11 11:33 UTC, gustavosr98 approved these changes
Perfecto, todo bien :+1:

2020-08-11 11:36 UTC, merged