FASE3-044 [E2E-TEST] Como cliente quiero acceder al sistema con login no federado
gustavosr98/petromiles pull request #17
Opened 2020-08-10 07:07 UTC by GabTovarUCAB

## Checklist para el pull request

- [ ] Este PR es un WIP (Work In Progress) para recibir _feedback_ de otros antes de culminar la funcionalidad

Para estar seguro de tu pull request, completa este checklist:

- [x] Estás haciendo el pull request a una rama diferente a la de master.
- [x] Estás haciendo el pull request desde la rama correcta.
- [x] El código compila sin errores.
- [x] Le coloque al título el mismo nombre que el de la tarjeta de Trello.

## Tipo de cambio para PetroMiles

- [x] Nueva historia de usuario completada
- [ ] Funcionalidad relacionada con API externas
- [ ] Corrección de algún problema
- [ ] Alguna mejora añadida

## Cambios propuestos

Automatización de pruebas E2E para Acceder a la plataforma Petromiles
contiene los siguientes casos:

1. Cuando el usuario no llena los campos de login.
2. Cuando el usuario trata de acceder dejando el campo de contraseña vacío.
3. Cuando el usuario trata de acceder dejando el campo de correo vacío.
4. Cuando el usuario trata de acceder con un correo equivocado.
5. Cuando el usuariotrata de acceder con una contraseña incorrecta.
6. Cuando el usuario llena todos los campos ingresando correctamente

[Tarjeta de Trello. FASE3-044](https://trello.com/c/A757t6Xv/196-fase3-044-e2e-test-como-cliente-quiero-acceder-al-sistema)

## ¿Cómo probar?

1. Correr el backend y el frontend.
2. iniciar la interfaz de Cypress, utilizando una ventana de comandos o powershell ubiquese en la carpeta front-end del proyecto (/`petromiles-frontend`) y ejecute el siguiente comando: `npm run cypress:open`. Abriendo la siguiente ventana:

![image](https://user-images.githubusercontent.com/55888512/89758501-f6a27880-dab5-11ea-814b-32f25b5fbdf2.png)

3. A continuacion, haga click en el testcase remarcado, de nombre `login-user.spec.js`
4. Iniciará la ejecucion de las pruebas para acceder a la pagina.

![image](https://user-images.githubusercontent.com/55888512/89758682-5dc02d00-dab6-11ea-98e9-c468d503c207.png)

5. Luego de que se ejecuten todas las pruebas, podrá ver los resultados de cypress.

![image](https://user-images.githubusercontent.com/55888512/89758722-73cded80-dab6-11ea-99b6-53268cd56bee.png)

2020-08-10 23:45 UTC, gustavosr98 requested changes
Tenemos el mismo detalle que en FASE3-044 #16

Un _**botón de ok**_ en un modal no nos asegura que la prueba haya realizado lo esperado. Te recomiendo utilizar por ejemplo un **assert** con el icono de alerta :warning: para los casos de error :+1:  
 
![image](https://user-images.githubusercontent.com/40648663/89841724-bab4f500-db41-11ea-929e-b935e11d277d.png)

2020-08-11 08:46 UTC, GabTovarUCAB commented
Agregado asserts para verificar las alertas que aparecen en las pruebas, y se mejoró los tiempos de cada prueba. 👍 

Ejemplo de como se verán las pruebas ahora, cuando se ejecuta cypress:

![image](https://user-images.githubusercontent.com/55888512/89876652-f1642d00-db8c-11ea-8748-fd8ac9f76787.png)

2020-08-11 09:16 UTC, christianneiraUCAB approved these changes

2020-08-11 11:25 UTC, gustavosr98 approved these changes
Excelente trabajo :100: :+1:

2020-08-11 19:16 UTC, merged