FASE3-046 [E2E-TEST] Como cliente quiero actualizar la información de mi perfil de usuario
gustavosr98/petromiles pull request #19
Opened 2020-08-10 19:53 UTC by GabTovarUCAB

## Checklist para el pull request

- [ ] Este PR es un WIP (Work In Progress) para recibir _feedback_ de otros antes de culminar la funcionalidad

Para estar seguro de tu pull request, completa este checklist:

- [x] Estás haciendo el pull request a una rama diferente a la de master.
- [x] Estás haciendo el pull request desde la rama correcta.
- [x] El código compila sin errores.
- [x] Le coloque al título el mismo nombre que el de la tarjeta de Trello.

## Tipo de cambio para PetroMiles

- [x] Nueva historia de usuario completada
- [ ] Funcionalidad relacionada con API externas
- [ ] Corrección de algún problema
- [ ] Alguna mejora añadida

## Cambios propuestos

Automatización de pruebas E2E para Recuperar contraseña de Usuario en la plataforma Petromiles
contiene los siguientes casos:

1. Cuando el usuario no llena el campo correspondiente y presiona el boton de recuperar contraseña.
2. Cuando el usuario ingresa un correo inválido.
3. Cuando el usuario solicita recuperar la contraseña satisfactoriamente.

[Tablero de Trello. FASE3-045](https://trello.com/c/i0Yg90Uf/198-fase3-046-e2e-test-como-cliente-quiero-actualizar-la-información-de-mi-perfil-de-usuario)

## ¿Cómo probar?

1. Correr el backend y el frontend.
2. Iniciar la interfaz de Cypress, utilizando una ventana de comandos o powershell ubiquese en la carpeta front-end del proyecto (`**/petromiles-frontend**`) y ejecute el siguiente comando: **`npm run cypress:open.`** Abriendo la siguiente ventana:

![image](https://user-images.githubusercontent.com/55888512/89821128-21271c80-db1c-11ea-9c52-98ecdd7fea57.png)

3. Haga click en la prueba llamada **`recover-password.spec.js`** que se encuentra resaltado en la imagen anterior
4. Comenzará a ejecutarse la prueba en Cypress.
5. Espere a que termine la ejecución y podrá observar los resultados de la prueba.

2020-08-10 23:50 UTC, gustavosr98 requested changes
Hay una prueba que esta fallando. Te recomiendo echarle un ojo a los tips de buenas practicas de Cypress para **encontrar de forma mas consistente un componente**

![image](https://user-images.githubusercontent.com/40648663/89842108-b6d5a280-db42-11ea-9a4e-ab0fffde9dce.png)

![image](https://user-images.githubusercontent.com/40648663/89842054-868e0400-db42-11ea-88e3-67034b7e7924.png)

2020-08-11 11:31 UTC, GabTovarUCAB commented
Arreglos realizados correctamente. 👍 
![image](https://user-images.githubusercontent.com/55888512/89889788-3fcef700-dba0-11ea-960f-57687a68446d.png)

2020-08-11 11:40 UTC, gustavosr98 approved these changes
Todo bien :1st_place_medal:

2020-08-11 13:02 UTC, michellealleyne approved these changes

2020-08-11 19:28 UTC, merged