FASE3-035: Implementación de esquemas de auditoría
gustavosr98/petromiles pull request #8
Opened 2020-08-08 18:22 UTC by mecoccaro

## Checklist para el pull request

**IMPORTANTE**: Revisa que tu PR no este dirigido a Master  
**NOTA**: Agrega al PR las etiquetas de Github que te parezcan esten relacionadas

- [ ] Este PR es un WIP (Work In Progress) para recibir _feedback_ de otros antes de culminar la funcionalidad

Para estar seguro de tu pull request, completa este checklist:

- [x ] Estás haciendo el pull request a una rama diferente a la de master.
- [x ] Estás haciendo el pull request desde la rama correcta.
- [x ] El código compila sin errores.
- [x ] Le coloque al título el mismo nombre que el de la tarjeta de Trello.

## Tipo de cambio para PetroMiles

- [ ] Nueva historia de usuario completada
- [ ] Funcionalidad relacionada con API externas
- [ ] Corrección de algún problema
- [x ] Alguna mejora añadida

## Cambios propuestos

Esquema de auditoria a los datos relacionados a la politica de privacidad, se registran logs de los cambios realizados a dichos datos.

- Se registra cuando se cambia informacion del usuario.
- Se registra quien hace el cambio.
- Se registran los datos antes y despues de ser cambiados.
- Se registra cuando se cambia el estado de una cuenta bancaria.

## ¿Cómo probar?

1. Inicie el front y el back
2. Cree una cuenta o inicie sesion.
3. Desde el usuario cambie algun dato desde el perfil del usuario ( las contraseña no entra en el esquema ), deberiamos ver un mensaje de verbose en los logs de esta manera
![imagen](https://user-images.githubusercontent.com/36824674/89717217-36684380-d982-11ea-8ecd-f64058dae4f2.png)

4. Vaya al administrador y haga cambios en los usuarios de la plataforma y vea los logs para ver mensajes similares al anterior.
5. Registre una cuenta bancaria a un usuario y bloquee o active la cuenta desde el usuario y desde el administrador y veremos un mensaje similar a este
![imagen](https://user-images.githubusercontent.com/36824674/89717240-75969480-d982-11ea-8ef3-16f52a73a6ed.png)

2020-08-08 20:10 UTC, JAA1998 commented
Cuando desde el administrador cambio el estado de una cuenta bancaria, en Previous data aparece que el estado anterior de la cuenta era verifying, cuando en realidad era bloqueado
![image](https://user-images.githubusercontent.com/40919117/89718959-7f73c400-d991-11ea-8391-50c4a2b0ea96.png)

Me pasa lo mismo cuando bloqueo una cuenta activa 
![image](https://user-images.githubusercontent.com/40919117/89718970-9adecf00-d991-11ea-8ff6-5344100a8f82.png)

2020-08-08 20:12 UTC, JAA1998 commented
Cuando cambio en el admin un parámetro funciona chévere y me muestra lo siguiente
![image](https://user-images.githubusercontent.com/40919117/89718995-cd88c780-d991-11ea-8d14-61483e95213a.png)

Pero creo que sería bueno que el mensaje aparezca con la misma estructura que todos, es decir: [verbose] [@Audit] ...

2020-08-08 20:13 UTC, JAA1998 commented
Los cambios en el perfil de un usuario funciona perfecto!

2020-08-08 20:27 UTC, gustavosr98 requested changes

2020-08-08 20:27 UTC, gustavosr98 commented on petromiles-backend/src/interceptors/audit-user.interceptor.ts
> +import * as winston from "winston";
No se usa
```suggestion
```

2020-08-08 20:27 UTC, gustavosr98 commented on petromiles-backend/src/interceptors/audit-user.interceptor.ts
> +import { BadRequestException, Inject } from '@nestjs/common';
```suggestion
import { Inject } from '@nestjs/common';
```

2020-08-08 20:27 UTC, gustavosr98 commented on petromiles-backend/src/interceptors/audit-user.interceptor.ts
> +
```suggestion
import { transform, isEqual, isObject } from 'lodash';
```

2020-08-08 20:27 UTC, gustavosr98 commented on petromiles-backend/src/interceptors/audit-user.interceptor.ts
> +    }
Para comparar la diferencia entre dos objectos

```suggestion
    }
    
    private differenceBetween(baseObject, newObject) {
    return this.changes(baseObject, newObject);
  }

  private changes(baseObject, newObject) {
    return transform(newObject, (result, value, key) => {
      if (!isEqual(value, baseObject[key])) {
        result[key] =
          isObject(value) && isObject(baseObject[key])
            ? this.changes(value, baseObject[key])
            : value;
      }
    });
  }
```

2020-08-08 20:27 UTC, gustavosr98 commented on petromiles-backend/src/interceptors/audit-user.interceptor.ts
> +        const body = JSON.stringify(req.body)
No creo que haga falta tener un objeto en forma de string
```suggestion
```

2020-08-08 20:27 UTC, gustavosr98 commented on petromiles-backend/src/interceptors/audit-bank-account.interceptor.ts
> +        this.logger.verbose(`[@Audit] Changes: [${body}]`)
Haria algo parecido a las sugerencias en cambios de datos del usuario

2020-08-09 04:01 UTC, mecoccaro commented
> 
> 
> Cuando desde el administrador cambio el estado de una cuenta bancaria, en Previous data aparece que el estado anterior de la cuenta era verifying, cuando en realidad era bloqueado
> ![image](https://user-images.githubusercontent.com/40919117/89718959-7f73c400-d991-11ea-8391-50c4a2b0ea96.png)
> 
> Me pasa lo mismo cuando bloqueo una cuenta activa
> ![image](https://user-images.githubusercontent.com/40919117/89718970-9adecf00-d991-11ea-8ff6-5344100a8f82.png)

Resuelto el problema!

2020-08-09 04:02 UTC, mecoccaro commented
> 
> 
> Cuando cambio en el admin un parámetro funciona chévere y me muestra lo siguiente
> ![image](https://user-images.githubusercontent.com/40919117/89718995-cd88c780-d991-11ea-8d14-61483e95213a.png)
> 
> Pero creo que sería bueno que el mensaje aparezca con la misma estructura que todos, es decir: [verbose] [@Audit] ...

Este log no es parte de la auditoria, los cambios en la plataforma no entran porque no son parte de la politica de privacidad de datos, por lo menos no por ahora!!! 👍

2020-08-09 04:02 UTC, mecoccaro commented on petromiles-backend/src/interceptors/audit-user.interceptor.ts
> +import * as winston from "winston";
Listo!

2020-08-09 04:03 UTC, mecoccaro commented on petromiles-backend/src/interceptors/audit-user.interceptor.ts
> +import { BadRequestException, Inject } from '@nestjs/common';
Listo!

2020-08-09 04:03 UTC, mecoccaro commented on petromiles-backend/src/interceptors/audit-user.interceptor.ts
> +    }
Aplicado! gracias por la sugerencia!

2020-08-09 04:03 UTC, mecoccaro commented on petromiles-backend/src/interceptors/audit-user.interceptor.ts
> +        const body = JSON.stringify(req.body)
Eliminado ya se usa como objeto! Gracias!

2020-08-09 04:21 UTC, michellealleyne approved these changes

2020-08-09 04:38 UTC, JAA1998 approved these changes
Excelente!

2020-08-10 22:47 UTC, gustavosr98 approved these changes
Buen trabajo :mechanical_arm:

2020-08-10 22:58 UTC, merged